// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $api_events_game from "./routes/api/events/game.ts";
import * as $api_events_games from "./routes/api/events/games.ts";
import * as $api_place from "./routes/api/place.ts";
import * as $auth_oauth2callback from "./routes/auth/oauth2callback.ts";
import * as $auth_signin from "./routes/auth/signin.ts";
import * as $auth_signout from "./routes/auth/signout.ts";
import * as $game_id_ from "./routes/game/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $start from "./routes/start.tsx";
import * as $GameDisplay from "./islands/GameDisplay.tsx";
import * as $GamesList from "./islands/GamesList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/api/events/game.ts": $api_events_game,
    "./routes/api/events/games.ts": $api_events_games,
    "./routes/api/place.ts": $api_place,
    "./routes/auth/oauth2callback.ts": $auth_oauth2callback,
    "./routes/auth/signin.ts": $auth_signin,
    "./routes/auth/signout.ts": $auth_signout,
    "./routes/game/[id].tsx": $game_id_,
    "./routes/index.tsx": $index,
    "./routes/start.tsx": $start,
  },
  islands: {
    "./islands/GameDisplay.tsx": $GameDisplay,
    "./islands/GamesList.tsx": $GamesList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
